/**
 * Android share target for Discover Anywhere (Phase 1).
 *
 * `android/` is a gitignored prebuild output, so the share target is declared here and
 * regenerated by `expo prebuild` / `expo run:android` instead of being hand-edited.
 *
 * The native layer only receives ACTION_SEND (text/plain) and re-emits the payload as a
 * `mystash://import?text=…` VIEW intent, which the existing expo-router deep-link
 * handling already understands. No validation, product logic, or networking lives in
 * native code.
 */

const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SHARE_ACTIVITY_NAME = '.ShareIntentActivity';
const SHARE_ACTIVITY_FILE = 'ShareIntentActivity.kt';
/** Mirrors MAX_SHARED_INPUT_LENGTH in src/ui/shareImport.ts and the backend domain. */
const MAX_SHARED_TEXT_LENGTH = 4000;

function shareActivityElement() {
  return {
    $: {
      'android:name': SHARE_ACTIVITY_NAME,
      'android:exported': 'true',
      'android:label': '@string/app_name',
      'android:theme': '@android:style/Theme.Translucent.NoTitleBar',
      'android:excludeFromRecents': 'true',
      'android:noHistory': 'true',
      'android:taskAffinity': '',
    },
    'intent-filter': [
      {
        action: [{ $: { 'android:name': 'android.intent.action.SEND' } }],
        category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
        data: [{ $: { 'android:mimeType': 'text/plain' } }],
      },
    ],
  };
}

/** Idempotent: re-running prebuild must not append a duplicate activity. */
function addShareIntentActivity(androidManifest) {
  const application = AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);
  application.activity = application.activity ?? [];
  const existingIndex = application.activity.findIndex(
    (activity) => activity?.$?.['android:name'] === SHARE_ACTIVITY_NAME,
  );
  const element = shareActivityElement();
  if (existingIndex >= 0) {
    application.activity[existingIndex] = element;
  } else {
    application.activity.push(element);
  }
  return androidManifest;
}

function shareIntentActivityKotlin(packageName) {
  return `package ${packageName}

import android.app.Activity
import android.content.Intent
import android.net.Uri
import android.os.Bundle

/**
 * Generated by plugins/withAndroidShareIntent.js — do not edit by hand.
 *
 * Receives Android Sharesheet ACTION_SEND (text/plain) and hands the payload to React
 * Native as a \`mystash://import\` deep link. Validation and all product logic live in JS.
 */
class ShareIntentActivity : Activity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    startActivity(importIntent(sharedText(intent)))
    finish()
  }

  /** Preserves the shared text verbatim, bounded so the deep link stays a sane size. */
  private fun sharedText(source: Intent?): String {
    if (source == null) return ""
    val extra = source.getCharSequenceExtra(Intent.EXTRA_TEXT)?.toString()
      ?: source.getStringExtra(Intent.EXTRA_SUBJECT)
      ?: ""
    return extra.trim().take(MAX_SHARED_TEXT_LENGTH)
  }

  private fun importIntent(text: String): Intent {
    val deepLink = Uri.Builder()
      .scheme(SCHEME)
      .authority(IMPORT_HOST)
      .appendQueryParameter(TEXT_PARAM, text)
      .build()

    return Intent(this, MainActivity::class.java).apply {
      action = Intent.ACTION_VIEW
      data = deepLink
      addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
    }
  }

  private companion object {
    const val SCHEME = "mystash"
    const val IMPORT_HOST = "import"
    const val TEXT_PARAM = "text"
    const val MAX_SHARED_TEXT_LENGTH = ${MAX_SHARED_TEXT_LENGTH}
  }
}
`;
}

function withShareIntentActivitySource(config) {
  return withDangerousMod(config, [
    'android',
    (modConfig) => {
      const packageName =
        AndroidConfig.Package.getPackage(modConfig) ?? modConfig.android?.package;
      if (!packageName) {
        throw new Error('withAndroidShareIntent: android.package is required');
      }
      const sourceDir = path.join(
        modConfig.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'java',
        ...packageName.split('.'),
      );
      fs.mkdirSync(sourceDir, { recursive: true });
      fs.writeFileSync(
        path.join(sourceDir, SHARE_ACTIVITY_FILE),
        shareIntentActivityKotlin(packageName),
        'utf8',
      );
      return modConfig;
    },
  ]);
}

function withAndroidShareIntent(config) {
  const withManifest = withAndroidManifest(config, (modConfig) => {
    modConfig.modResults = addShareIntentActivity(modConfig.modResults);
    return modConfig;
  });
  return withShareIntentActivitySource(withManifest);
}

module.exports = withAndroidShareIntent;
module.exports.addShareIntentActivity = addShareIntentActivity;
module.exports.shareIntentActivityKotlin = shareIntentActivityKotlin;
module.exports.SHARE_ACTIVITY_NAME = SHARE_ACTIVITY_NAME;
module.exports.MAX_SHARED_TEXT_LENGTH = MAX_SHARED_TEXT_LENGTH;
